### ISSUE TITLE
About aboard () method of problem

### ISSUE THREAD

**Issue by whevether** [fpellet/jquery.ajaxFile#1]
Hello!  In ajaxfile, I do not understand the logic! Callback function should trigger at what time

2.Sample file within textarea tags garbled! Don't know why?
Thanks for the help answers!   My English is not very good.

**Comment by fpellet** [comment]
Hi

I'm not sure understand your problem. Without jquery, send function return an promise. Your problem is on client side or server side ?
Can you send an example?

Textarea in the server response is just a hack, for older browser, if the status code isn't 200.
More informations : https://github.com/fpellet/jquery.ajaxFile#standard-response-format

**Comment by whevether** [comment]
Hello, I'm sorry, I'm a Chinese student ... English is not so good, just put "Abord ()" this approach wrong. you have solved my problem. I didn't look carefully you document entitled, thank you for your kind answers ...
